disabled_rules:
  - identifier_name
  - leading_whitespace
  - line_length
  - todo

trailing_comma:
  mandatory_comma: true

cyclomatic_complexity:
  ignores_case_statements: true

excluded:
  - "**/.build"
  - "**/build"
